variables:
  AZURE_BUILD: true

trigger:
  tags:
    include:
      - v*

pr: none

jobs:
  - job: 'PackageWinOsx'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 10
    displayName: 'Build wheels ::'
    pool:
      vmImage: $(image.name)

    strategy:
      matrix:
        osx - python37:
          image.name: 'macOS-10.15'
          python.version: '3.7'
        osx - python38:
          image.name: 'macOS-10.15'
          python.version: '3.8'
        osx - python39:
          image.name: 'macOS-10.15'
          python.version: '3.9'
        osx - python310:
          image.name: 'macOS-10.15'
          python.version: '3.10'

        windows - python37:
          image.name: 'windows-2019'
          python.version: '3.7'
        windows - python38:
          image.name: 'windows-2019'
          python.version: '3.8'
        windows - python39:
          image.name: 'windows-2019'
          python.version: '3.9'
        windows - python310:
          image.name: 'windows-2019'
          python.version: '3.10'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
        displayName: 'Use Python $(python.version)'

      - script: env
        displayName: 'List enviromental variables'

      - script: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel pytest
          python -m pip install cython
          python -m pip install numpy==1.16.6
        displayName: 'Install job dependencies'

      - script: python -m pip freeze
        displayName: 'List dependency versions'

      - script: python setup.py bdist_wheel
        displayName: 'Build wheel'

      # Since Python automatically adds `cwd` to `sys.path`, it's important we remove the local folder
      # containing our code from the working directory. Otherwise, the tests will use the local copy
      # instead of the installed package. We can easily achieve this by renaming the source folder.
      - bash: mv openTSNE src
        displayName: 'Remove source files from path'

      - bash: ls -lRh dist
        displayName: 'List built files'

      - bash: python -m pip install -vv --force-reinstall --find-links dist openTSNE
        displayName: 'Install wheel'

      - script: pip install pynndescent
        displayName: 'Install optional dependencies - pynndescent'
        condition: ne(variables['python.version'], '3.6')  # llvm-lite doesn't support py36 from v0.37 onwards

      - script: pip install hnswlib
        displayName: 'Install optional dependencies - hnswlib'

      - script: pytest -v
        timeoutInMinutes: 15
        displayName: 'Run unit tests'

      - task: CopyFiles@2
        condition: eq(variables['Agent.JobStatus'], 'Succeeded')
        inputs:
          contents: dist/**
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        condition: eq(variables['Agent.JobStatus'], 'Succeeded')
        inputs:
          artifactName: 'build'
          pathtoPublish: $(Build.ArtifactStagingDirectory)


  - job: 'PackageLinux'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 10
    displayName: 'Build wheels :: linux -'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        python37:
          python: '/opt/python/cp37-cp37m/bin'
          python.version: '3.7'
        python38:
          python: '/opt/python/cp38-cp38/bin'
          python.version: '3.8'
        python39:
          python: '/opt/python/cp39-cp39/bin'
          python.version: '3.9'

    container:
      image: quay.io/pypa/manylinux2010_x86_64:latest
      options: -e PLAT=manylinux2010_x86_64

    steps:
      - bash: ls -R /opt/python
        displayName: 'List available Python binaries'

      - bash: $(python)/pip install --user pytest
        displayName: 'Install job dependencies'

      # Build and install the wheel
      - bash: .ci/build_wheels.sh
        displayName: 'Build wheels'
        env:
          PYBIN: $(python)

      # Since Python automatically adds `cwd` to `sys.path`, it's important we remove the local folder
      # containing our code from the working directory. Otherwise, the tests will use the local copy
      # instead of the installed package. We can easily achieve this by renaming the source folder.
      - bash: mv openTSNE src
        displayName: 'Remove source files from path'

      - script: $(python)/pip install pynndescent
        displayName: 'Install optional dependencies - pynndescent'
        condition: false  # llvm-lite doesn't support py36 from v0.37 onwards, and the llvmlite version wasn't built for manylinux2010

      - script: $(python)/pip install hnswlib
        displayName: 'Install optional dependencies - hnswlib'

      - script: $(python)/python -m pytest -v
        timeoutInMinutes: 15
        displayName: 'Run unit tests'

      - bash: |
          ls -lRh wheelhouse
          mkdir -p dist
          cp wheelhouse/openTSNE*manylinux*.whl dist/
        displayName: 'Copy files to dist folder'

      - task: CopyFiles@2
        condition: eq(variables['Agent.JobStatus'], 'Succeeded')
        inputs:
          contents: dist/**
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        condition: eq(variables['Agent.JobStatus'], 'Succeeded')
        inputs:
          artifactName: 'build'
          pathtoPublish: $(Build.ArtifactStagingDirectory)


  - job: 'sdist'
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 10
    displayName: 'Package source distribution'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7'
        inputs:
          versionSpec: '3.7'

      - script: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel pytest
          python -m pip install cython
          python -m pip install numpy==1.16.6
        displayName: 'Install job dependencies'

      - script: python -m pip freeze
        displayName: 'List dependency versions'

      - script: python setup.py sdist
        displayName: 'Build sdist'

      # Since Python automatically adds `cwd` to `sys.path`, it's important we remove the local folder
      # containing our code from the working directory. Otherwise, the tests will use the local copy
      # instead of the installed package. We can easily achieve this by renaming the source folder.
      - bash: mv openTSNE src
        displayName: 'Remove source files from path'

      - bash: ls -lRh dist
        displayName: 'List built files'

      - bash: python -m pip install --force-reinstall --find-links dist openTSNE
        displayName: 'Install package'

      - script: |
          python -m pip install pynndescent
          python -m pip install hnswlib
        displayName: 'Install optional dependencies'

      - script: pytest -v
        timeoutInMinutes: 15
        displayName: 'Run unit tests'

      - task: CopyFiles@2
        condition: eq(variables['Agent.JobStatus'], 'Succeeded')
        inputs:
          contents: dist/**
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        condition: eq(variables['Agent.JobStatus'], 'Succeeded')
        inputs:
          artifactName: 'build'
          pathtoPublish: $(Build.ArtifactStagingDirectory)
